source "https://rubygems.org"
# ill-formed => gem 'source', 'https://rubygems.org'
ruby "2.4.2"
# ill-formed => gem 'ruby', '2.4.2'
# Could not find gem 'ruby (= 2.4.2)'
# In any of the gem sources listed in your Gemfile
#
# Date of this Update to Gem-template file ver 01-31-2018
# 
# Hello!
#
# This is where you manage which version of the 'Jekyll server' is used to run your GitHub Pages repo.
#
# The 'Gemfile' (no extension suffix) sits in the root directory of your repo.
#
# This 'Gemfile' is where you manage the versioning for the 'Jekyll server' and all of its dependencies.
#
# At the beginning, when you establish GitHub Pages via the 'docs' folder in the settings page of your new repo over at GitHub ...
# 
# A new 'Gemfile' will be auto-populated remotely with a simply one-line showing your selected theme.
#
# Note. To select a theme, make sure you have a copy of an index.md page sitting inside the 'docs' folder at your remote master.
#
# After successfully synching your local master with the remote master, you will need to enhance the beginning 'Gemfile'.
#
# Import the contents of this template into your new 'Gemfile' and synch again with the remote master.
#
# When you run the command 'bundle install' from a local Terminal prompt at the root directory of your repo ...
# 
# A 'Gemfile.lock' file will be auto-generated by the 'Gem Bundler' program that fixes the dependencies shown here.
#
# Note. You will need to install a copy of the 'Gem Bundler' program onto your development machine
#
# From the global Terminal prompt, run the following command statement:
#
# gem install bundler
#
# Once you have successfully installed the 'Gem Bundler' program to your development machine ...
#
# You may then run the following command from a Terminal prompt to check the current version of 'Gem Bundler', as follows:
# 
# bundler --version
#
# You may also run the following command from a Terminal prompt to check the location of your new 'Gem Bundler' version, as follows:
#
# which bundler
#
# The 'Gem Bundler' program will notify you via the Terminal at the next update operation if an upgrade to your version of the 'Gem Bundler' program is available.
# 
# To upgrade your version of the 'Gem Bundler' program ...
# 
# Type the following command at a local Terminal prompt,
#
# gem update bundler
#
# Note. You only need to install the 'Gem Bundler' program once.
#
# It is not necessary to install the 'Gem Bundler' program every time you create a separate repo. 
#
# To instantiate an instance of the 'Jekyll server' on your development machine ...
#
# You will need to install the 'Ruby Version Manager' onto your development machine.
#
# And, then install a copy of 'Ruby ver 2.4.2' with the help of your new 'Ruby Version Manager' working through Homebrew.
#
# Note. To avoid the default system Ruby that was factory installed a-way back when you bought your development machine ...
#
# Always preface your Terminal sesson with the following Ruby command:
#
# rvm use 2.4.2
#
# Once you have successfully installed 'Ruby ver 2.4.2' to your development machine ...
#
# You may now install the local 'Jekyll server' program via the following global Terminal command ...
#
# gem install jekyll
#
# Note. Designating the version of the 'Jekyll server' when installing via Bundle update, or via the initial Bundle install ...
# 
# Will not survive the 'Jekyll-docs' installation
#
# Once the 'Jekyll server' program has been installed to your development machine ...
#
# Note. If you are planning to use 'GitHub Pages' ...
# 
# Then, comment out the following version statement to retain your superior version copy locally
#
gem 'jekyll', '3.6.2'
#
# Note. The version of 'Jekyll docs' should match the installed version of 'Jekyll' from above.
# In other words, you should install the 'jekyll-docs' gem version = 3.6.2 to use the 'jekyll docs' command
#
# However, when attempting ...
# gem install jekyll-docs v3.6.2
# From the global Terminal command, returns ...
# Warning. Could not find a valid gem 'v3.6.2' (>= 0) in any repository
#
# After successfully installing the 'Jekyll server' program from the global Terminal prompt, as above ...
#
# You may also install the 'jekyll-docs' program from the global Terminal prompt of your development machine, as follows:
#
# gem install jekyll-docs
#
# Once the 'Jekyll docs' program has been installed to your development machine ...
#
# Then, comment out the following version statement to retain your superior version copy locally
#
gem 'jekyll-docs', '3.6.2'
#
# To run 'Jekyll docs' locally ...
#
# Type the following command statement from the global Terminal prompt ...
#
# When you are ready to review the documentation.
#
# A new 'Jekyll server' instance will auto-launch in your Chrome browser window at the default port 4000, as follows:
#
# jekyll docs serve
#
# Congratulations! You have installed manually the most recent version of Jekyll docs ( ver 3.7.2 )
#
# And,
#
# Congratulations! You have installed manually the most recent version of Jekyll server ( ver 3.7.2 )
#
# Note. You only need to install the 'Jekyll server' program one time on your development machine.
#
# It is not necessary to install the 'Jekyll server' program every time you create a separate repo. 
#
# To check the disk location of your new 'Jekyll server' program, run the following command from a local Terminal prompt:
#
# which jekyll
#
# To check the version of your newly installed 'Jekyll server' program ...
# 
# Run the following command from a local Terminal prompt:
#
# jekyll -v
#
# When you want to use a different version of the 'Jekyll server' ...
#
# Run the following command from a Terminal prompt
#
# bundle update github-pages
#
# The 'Gem Bundler' program will then install the 'Jekyll server' version you have indicated.
#
# Optionally, you may run the following command from the Terminal prompt to ensure your copy of the 'Jekyll server' is up and running.
#
# bundle exec jekyll serve
#
# To start a local 'Jekyll server' instance ...
#
# Open up the /docs directory of your repo from inside Visual Studio Code.
#
# Next, type the following command at the 'Integrated Terminal View' of Visual Studio Code:
#
# jekyll serve --watch --baseurl "" -o
#
# The Jekyll server will auto-navigate to the default local URL http://localhost:4000/ at your Chrome browser and display your new repo locally.
#
# To manually target the 'Jekyll server' locally at another port other than the default port 4000 ...
#
# Type the following variation of the command at your Terminal prompt:
#
# jekyll serve --watch --baseurl "" --port 4001 -o
#
# The default theme for new Jekyll sites is 'jekyll-theme-minimal 0.1.0'.
# Note. You may change the theme to anything you like via the config dot yaml page located in the `docs` folder of your new repo
# If you do decide to manage the theme of your repo from the config dot yaml page, then comment out both the default and your selected themes here, as follows:
#
# gem 'jekyll-theme-cayman', '0.1.0'
# gem 'jekyll-theme-minimal', 0.1.0'
# 
# Happy Jekyll-ing!
#
# Note. To upgrade all, run `bundle update` from the command line.
#
# github-pages, 175 requires activesupport, 429
gem 'activesupport', '4.2.9'
#
gem 'github-pages', '175'
#
# Note. The ''github-markdown' dependency is no longer designated at the online GitHub Pages dependency chart
# C=> https://pages.github.com/versions/
# gem 'github-markdown'
#
gem 'kramdown', '1.16.2'
#
gem 'jekyll-gist', '1.4.1'
#
gem 'jekyll-coffeescript', '1.0.2'
#
gem 'jekyll-paginate', '1.1.0'
#
gem 'jekyll-seo-tag', '2.3.0'
#
gem 'jekyll-sitemap', '1.1.1'
#
gem 'minima', '2.1.1'
#
gem 'sass', '3.5.5'
#
gem 'safe_yaml', '1.0.4'
#
gem 'jekyll-titles-from-headings', '0.5.0'
#
gem 'jemoji', '0.8.1'
#
gem 'liquid', '4.0.0'
#
gem 'listen', '3.0.6'
#
# Override the GitHub Pages online Dependency Chart Dtd 012418;
# ver 1.7.2 of the Nokogiri dependency has a Security issue
gem 'nokogiri', '1.8.1'
# 
gem 'rouge', '2.2.1'
#
gem 'jekyll-default-layout', '0.1.4'
#
gem 'jekyll-github-metadata', '2.9.3'
#
gem 'jekyll-mentions', '1.2.0'
#
gem 'jekyll-optional-front-matter', '0.3.0'
#
gem 'jekyll-readme-index', '0.2.0'
#
gem 'jekyll-redirect-from', '0.12.1'
#
gem 'jekyll-relative-links', '0.5.2'
#
gem 'jekyll-remote-theme', '0.2.3'
#
gem 'jekyll-sass-converter', '1.5.0'
#
gem 'jekyll-swiss', '0.4.0'
#
gem 'github-pages-health-check', '1.3.5'
#
gem 'html-pipeline', '2.7.1'
#
gem 'jekyll-avatar', '0.5.0'
#
gem 'jekyll-commonmark-ghpages', '0.1.3'
#
# If you have any other Jekyll plugins, put them here ...
# group: 'jekyll_plugins' do
gem 'jekyll-feed', '0.9.2'
# end
#
# Note. Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
#