package client;

/**
 * The 'Client' class is a new class designed to be the parent class of...
 * Both the 'Buyer' and the 'Seller' classes. Where similar data match, such data will be transferred to...
 * This 'Client' class. Thus, (in the refactoring process) both the 'Buyer' class and the 'Seller' class...
 * Will extend the new 'Client' class.
 * ============================================================================================
 * @param 1c.) String name - An object string parameter derived from the original (old)...
 * 'SellerInterface_old' class, now equal to the variable 'categoryName'
 * ============================================================================================
 * @param 2c.) Product product - An object product parameter derived from the original (old)...
 * 'SellerInterface_old' class, now equal to the variable 'itemProduct'
 * ============================================================================================
 * @author rwebaz http://about.me/rwebaz */

public class Client {
	// More to come...
}
